-- ===========================================
-- DATABASE STRUCTURE FOR ACONSA
-- PostgreSQL
-- ===========================================
DROP TABLE IF EXISTS public.reportes_generados CASCADE;
DROP TABLE IF EXISTS public.permisos CASCADE;
DROP TABLE IF EXISTS public.menu CASCADE;
DROP TABLE IF EXISTS public.detalles_avaluos CASCADE;
DROP TABLE IF EXISTS public.detalles_compras CASCADE;
DROP TABLE IF EXISTS public.movimientos_inventario CASCADE;
DROP TABLE IF EXISTS public.alertas_inventario CASCADE;
DROP TABLE IF EXISTS public.compras CASCADE;
DROP TABLE IF EXISTS public.historial_alertas CASCADE;
DROP TABLE IF EXISTS public.usuarios CASCADE;
DROP TABLE IF EXISTS public.detalles_vehiculos CASCADE;
DROP TABLE IF EXISTS public.vehiculos CASCADE;
DROP TABLE IF EXISTS public.detalles_maquinarias CASCADE;
DROP TABLE IF EXISTS public.maquinarias CASCADE;
DROP TABLE IF EXISTS public.costos_indirectos_servicios CASCADE;
DROP TABLE IF EXISTS public.costos_directos_servicios CASCADE;
DROP TABLE IF EXISTS public.servicios CASCADE;
DROP TABLE IF EXISTS public.avaluos CASCADE;
DROP TABLE IF EXISTS public.materiales CASCADE;
DROP TABLE IF EXISTS public.categorias CASCADE;
DROP TABLE IF EXISTS public.detalles_empleados CASCADE;
DROP TABLE IF EXISTS public.proyectos CASCADE;
DROP TABLE IF EXISTS public.proveedores CASCADE;
DROP TABLE IF EXISTS public.categorias_proveedor CASCADE;
DROP TABLE IF EXISTS public.clientes CASCADE;
DROP TABLE IF EXISTS public.empleados CASCADE;
DROP TABLE IF EXISTS public.roles CASCADE;

-- ROLES
CREATE TABLE roles (
rol_id              INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cargo               VARCHAR(100) NOT NULL,
descripcion         VARCHAR(150),
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ
);

-- EMPLEADOS
CREATE TABLE empleados (
empleado_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombres             VARCHAR(100) NOT NULL,
apellidos           VARCHAR(100) NOT NULL,
cedula              VARCHAR(25) NOT NULL,
rol_id              INT NOT NULL,
fecha_nacimiento    DATE NOT NULL,
fecha_contratacion  DATE NOT NULL,
direccion           VARCHAR(150),
pais                VARCHAR(50),
telefono            VARCHAR(15),
correo              VARCHAR(100),
reportes            INT,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_empleados_rol
FOREIGN KEY (rol_id)
REFERENCES roles (rol_id),

CONSTRAINT fk_empleados_jefe
FOREIGN KEY (reportes)
REFERENCES empleados (empleado_id),

CONSTRAINT uq_empleados_cedula
UNIQUE (cedula),

CONSTRAINT chk_empleados_cedula
CHECK (cedula ~ '^[0-9]{13}[A-Za-z]$'),

CONSTRAINT chk_empleados_telefono
CHECK (telefono IS NULL OR telefono ~ '^[0-9]{8,15}$'),

CONSTRAINT chk_empleados_correo
CHECK (correo IS NULL OR correo LIKE '%_@%.%')
);

-- CLIENTES
CREATE TABLE clientes (
cliente_id            CHAR(5) PRIMARY KEY,
tipo_cliente          VARCHAR(30) NOT NULL,
numero_identificacion VARCHAR(50),
nombre_empresa        VARCHAR(100) NOT NULL,
nombre_contacto       VARCHAR(100),
cargo_contacto        VARCHAR(50),
direccion             VARCHAR(150),
ciudad                VARCHAR(100),
pais                  VARCHAR(50),
telefono              VARCHAR(20),
correo                VARCHAR(100),
fecha_creacion        TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion   TIMESTAMPTZ,
fecha_eliminacion     TIMESTAMPTZ,

CONSTRAINT chk_clientes_tipo_cliente
CHECK (tipo_cliente IN ('Persona Natural', 'Persona Jurídica')),

CONSTRAINT chk_clientes_identificacion
CHECK (numero_identificacion IS NULL OR numero_identificacion ~ '^[A-Za-z0-9]+$'),

CONSTRAINT chk_clientes_telefono
CHECK (telefono IS NULL OR telefono ~ '^[0-9]{8,15}$'),

CONSTRAINT chk_clientes_correo
CHECK (correo IS NULL OR correo LIKE '%_@%.%')
);

-- CATEGORÍAS DE PROVEEDOR
CREATE TABLE categorias_proveedor (
categoria_proveedor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_categoria       VARCHAR(100) NOT NULL,
descripcion            VARCHAR(150),
fecha_creacion         TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion    TIMESTAMPTZ,
fecha_eliminacion      TIMESTAMPTZ
);

-- PROVEEDORES
CREATE TABLE proveedores (
proveedor_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
categoria_proveedor_id INT NOT NULL,
nombre_empresa         VARCHAR(100) NOT NULL,
nombre_contacto        VARCHAR(100),
cargo_contacto         VARCHAR(50),
direccion              VARCHAR(150),
ciudad                 VARCHAR(100),
pais                   VARCHAR(50),
telefono               VARCHAR(15),
correo                 VARCHAR(100),
fecha_creacion         TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion    TIMESTAMPTZ,
fecha_eliminacion      TIMESTAMPTZ,

CONSTRAINT fk_proveedores_categoria
FOREIGN KEY (categoria_proveedor_id)
REFERENCES categorias_proveedor (categoria_proveedor_id),

CONSTRAINT chk_proveedores_telefono
CHECK (telefono IS NULL OR telefono ~ '^[0-9]{8,15}$'),

CONSTRAINT chk_proveedores_correo
CHECK (correo IS NULL OR correo LIKE '%_@%.%')
);

-- PROYECTOS
CREATE TABLE proyectos (
proyecto_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
cliente_id          CHAR(5) NOT NULL,
nombre_proyecto     VARCHAR(100) NOT NULL,
descripcion         VARCHAR(150),
ubicacion           VARCHAR(100),
fecha_inicio        DATE NOT NULL,
fecha_fin           DATE,

tiempo_total_dias   INT GENERATED ALWAYS AS (
fecha_fin - fecha_inicio
) STORED,

presupuesto_total   NUMERIC(18,2) NOT NULL,
estado              VARCHAR(50) NOT NULL DEFAULT 'En Espera',
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_proyectos_cliente
FOREIGN KEY (cliente_id)
REFERENCES clientes (cliente_id),

CONSTRAINT chk_proyectos_presupuesto
CHECK (presupuesto_total > 0),

CONSTRAINT chk_proyectos_estado
CHECK (estado IN ('En Espera','Activo','Completado','Cancelado')),

CONSTRAINT chk_proyectos_fechas
CHECK (fecha_fin IS NULL OR fecha_fin >= fecha_inicio)
);

-- DETALLES EMPLEADOS
CREATE TABLE detalles_empleados (
detalle_empleado_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
empleado_id          INT NOT NULL,
proyecto_id          INT NOT NULL,
fecha_de_proyecto    DATE DEFAULT CURRENT_DATE,
fecha_creacion       TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion  TIMESTAMPTZ,
fecha_eliminacion    TIMESTAMPTZ,

CONSTRAINT fk_detalle_empleado
FOREIGN KEY (empleado_id)
REFERENCES empleados (empleado_id),

CONSTRAINT fk_detalle_proyecto
FOREIGN KEY (proyecto_id)
REFERENCES proyectos (proyecto_id),

CONSTRAINT uq_detalles_empleados_empleado_proyecto
UNIQUE (empleado_id, proyecto_id)
);

-- CATEGORÍAS
CREATE TABLE categorias (
categoria_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_categoria    VARCHAR(100) NOT NULL,
descripcion         VARCHAR(150) NOT NULL,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ
);

-- MATERIALES
CREATE TABLE materiales (
material_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_material     VARCHAR(100) NOT NULL,
categoria_id        INT,
descripcion         VARCHAR(150),
unidad_de_medida    VARCHAR(100) NOT NULL,
cantidad_en_stock   INT NOT NULL,
stock_minimo        INT NOT NULL DEFAULT 10,
precio_unitario     NUMERIC(18,2) NOT NULL,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_materiales_categoria
FOREIGN KEY (categoria_id)
REFERENCES categorias (categoria_id),

CONSTRAINT chk_materiales_stock
CHECK (cantidad_en_stock >= stock_minimo),

CONSTRAINT chk_materiales_stock_minimo
CHECK (stock_minimo >= 10),

CONSTRAINT chk_materiales_precio
CHECK (precio_unitario > 0)
);

-- ALERTAS INVENTARIO
CREATE TABLE alertas_inventario (
alerta_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
material_id         INT NOT NULL,
tipo_alerta         VARCHAR(50) NOT NULL,
mensaje             VARCHAR(250) NOT NULL,
stock_actual        INT NOT NULL,
stock_minimo        INT NOT NULL DEFAULT 10,
estado              VARCHAR(30) DEFAULT 'Pendiente',
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_atendida      TIMESTAMPTZ,
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_alertas_materiales
FOREIGN KEY (material_id)
REFERENCES materiales (material_id),

CONSTRAINT chk_alertas_tipo
CHECK (tipo_alerta IN ('Stock Bajo', 'Inventario Crítico')),

CONSTRAINT chk_alertas_estado
CHECK (estado IN ('Pendiente', 'Atendida', 'Cancelada'))
);

-- AVALUOS
CREATE TABLE avaluos (
avaluo_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
proyecto_id         INT NOT NULL,
descripcion         VARCHAR(200),
monto_ejecutado     NUMERIC(18,2) NOT NULL,

fecha_inicio        TIMESTAMP NOT NULL,
fecha_fin           TIMESTAMP NOT NULL,

tiempo_total_dias   INT GENERATED ALWAYS AS (
fecha_fin::date - fecha_inicio::date
) STORED,

fecha_creacion      TIMESTAMP DEFAULT NOW(),
fecha_actualizacion TIMESTAMP,
fecha_eliminacion   TIMESTAMP,

CONSTRAINT fk_avaluos_proyecto
FOREIGN KEY (proyecto_id)
REFERENCES proyectos(proyecto_id),

CONSTRAINT chk_avaluos_monto
CHECK (monto_ejecutado >= 0),

CONSTRAINT chk_avaluos_fechas
CHECK (fecha_fin >= fecha_inicio)
);

-- SERVICIOS
CREATE TABLE servicios (
servicio_id            INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre_servicio        VARCHAR(100) NOT NULL,
descripcion            VARCHAR(200),
total_costo_directo    DECIMAL(18,2) NOT NULL,
total_costo_indirecto  DECIMAL(18,2) NOT NULL,

costo_venta            DECIMAL(18,2)
GENERATED ALWAYS AS (
total_costo_directo + total_costo_indirecto
) STORED,

fecha_creacion         TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion    TIMESTAMPTZ,
fecha_eliminacion      TIMESTAMPTZ,

CONSTRAINT chk_servicios_total_costo_directo
CHECK (total_costo_directo > 0),

CONSTRAINT chk_servicios_total_costo_indirecto
CHECK (total_costo_indirecto > 0)
);

-- COSTOS DIRECTOS SERVICIOS
CREATE TABLE costos_directos_servicios (
costo_directo_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
servicio_id        INT NOT NULL,
material_id        INT NOT NULL,
cantidad_material  INT NOT NULL,
unidad_de_medida   VARCHAR(50) NOT NULL,
precio_unitario    NUMERIC(18,2) NOT NULL,

costo_material NUMERIC(18,2)
GENERATED ALWAYS AS (
precio_unitario * cantidad_material
) STORED,

mano_obra NUMERIC(18,2)
GENERATED ALWAYS AS (
(precio_unitario * cantidad_material) * 0.40
) STORED,

equipos_transporte_herramientas NUMERIC(18,2)
GENERATED ALWAYS AS (
(precio_unitario * cantidad_material) * 0.10
) STORED,

total_costo_directo NUMERIC(18,2)
GENERATED ALWAYS AS (
(precio_unitario * cantidad_material) +
((precio_unitario * cantidad_material) * 0.40) +
((precio_unitario * cantidad_material) * 0.10)
) STORED,

fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_cds_servicio
FOREIGN KEY (servicio_id)
REFERENCES servicios (servicio_id),

CONSTRAINT fk_cds_material
FOREIGN KEY (material_id)
REFERENCES materiales (material_id),

CONSTRAINT chk_cds_cantidad
CHECK (cantidad_material > 0),

CONSTRAINT chk_cds_precio
CHECK (precio_unitario > 0)
);

-- COSTOS INDIRECTOS SERVICIOS
CREATE TABLE costos_indirectos_servicios (
costo_indirecto_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
servicio_id            INT NOT NULL,
costo_directo_id       INT NOT NULL,
total_costo_directo    DECIMAL(18,2) NOT NULL,

administracion         DECIMAL(18,2)
GENERATED ALWAYS AS (
total_costo_directo * 0.05
) STORED,

operacion              DECIMAL(18,2)
GENERATED ALWAYS AS (
total_costo_directo * 0.10
) STORED,

utilidad               DECIMAL(18,2)
GENERATED ALWAYS AS (
total_costo_directo * 0.15
) STORED,

precio_unitario        DECIMAL(18,2)
GENERATED ALWAYS AS (
(total_costo_directo * 0.05) +
(total_costo_directo * 0.10) +
(total_costo_directo * 0.15)
) STORED,

total_costo_indirecto  DECIMAL(18,2)
GENERATED ALWAYS AS (
(total_costo_directo * 0.05) +
(total_costo_directo * 0.10) +
(total_costo_directo * 0.15)
) STORED,

fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_cis_servicio
FOREIGN KEY (servicio_id)
REFERENCES servicios(servicio_id),

CONSTRAINT fk_cis_costo_directo
FOREIGN KEY (costo_directo_id)
REFERENCES costos_directos_servicios(costo_directo_id),

CONSTRAINT chk_cis_total_directo
CHECK (total_costo_directo > 0)
);

-- MAQUINARIAS
CREATE TABLE maquinarias (
maquinaria_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
proveedor_id        INT,
nombre_maquinaria   VARCHAR(100) NOT NULL,
marca               VARCHAR(50),
modelo              VARCHAR(50),
precio_por_hora     NUMERIC(18,2) NOT NULL,
descripcion         VARCHAR(200),
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_maquinarias_proveedor
FOREIGN KEY (proveedor_id)
REFERENCES proveedores (proveedor_id),

CONSTRAINT chk_maquinarias_precio
CHECK (precio_por_hora >= 0)
);

-- DETALLES MAQUINARIAS
CREATE TABLE detalles_maquinarias (
detalle_maquinaria_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
proyecto_id           INT,
maquinaria_id         INT,
horas_utilizadas      INT,
fecha_inicio_renta    DATE NOT NULL,
fecha_fin_renta       DATE,
estado                VARCHAR(30),
fecha_creacion        TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion   TIMESTAMPTZ,
fecha_eliminacion     TIMESTAMPTZ,

CONSTRAINT fk_detalle_proyecto_maq
FOREIGN KEY (proyecto_id)
REFERENCES proyectos (proyecto_id),

CONSTRAINT fk_detalle_maquinaria
FOREIGN KEY (maquinaria_id)
REFERENCES maquinarias (maquinaria_id),

CONSTRAINT chk_detalles_maquinarias_estado
CHECK (estado IS NULL OR estado IN ('Activa','Finalizada','Cancelada')),

CONSTRAINT chk_detalles_maquinarias_horas
CHECK (horas_utilizadas IS NULL OR horas_utilizadas >= 0),

CONSTRAINT chk_detalles_maquinarias_fechas
CHECK (fecha_fin_renta IS NULL OR fecha_fin_renta >= fecha_inicio_renta)
);

-- VEHÍCULOS
CREATE TABLE vehiculos (
vehiculo_id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
proveedor_id        INT,
marca               VARCHAR(50) NOT NULL,
modelo              VARCHAR(50) NOT NULL,
anio                INT,
placa               VARCHAR(15) UNIQUE NOT NULL,
tipo_de_vehiculo    VARCHAR(30),
tipo_de_combustible VARCHAR(40),
estado              VARCHAR(20),
fecha_registro      DATE,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_vehiculos_proveedor
FOREIGN KEY (proveedor_id)
REFERENCES proveedores (proveedor_id),

CONSTRAINT chk_vehiculos_anio
CHECK (anio IS NULL OR anio >= 1886),

CONSTRAINT chk_vehiculos_estado
CHECK (estado IS NULL OR estado IN ('Disponible','En Mantenimiento','No Disponible')),

CONSTRAINT chk_vehiculos_combustible
CHECK (
tipo_de_combustible IS NULL
OR tipo_de_combustible IN ('Diésel', 'Regular', 'Gasolina Super')
)
);

-- DETALLES VEHÍCULOS
CREATE TABLE detalles_vehiculos (
detalle_vehiculo_id  INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
empleado_id          INT NOT NULL,
vehiculo_id          INT NOT NULL,
fecha_asignacion     DATE NOT NULL,
fecha_fin_asignacion DATE,
descripcion          VARCHAR(100),
fecha_creacion       TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion  TIMESTAMPTZ,
fecha_eliminacion    TIMESTAMPTZ,

CONSTRAINT fk_detalle_empleado_veh
FOREIGN KEY (empleado_id)
REFERENCES empleados (empleado_id),

CONSTRAINT fk_detalle_vehiculo
FOREIGN KEY (vehiculo_id)
REFERENCES vehiculos (vehiculo_id),

CONSTRAINT chk_detalles_vehiculos_fechas
CHECK (fecha_fin_asignacion IS NULL OR fecha_fin_asignacion >= fecha_asignacion)
);

-- USUARIOS
CREATE TABLE usuarios (
usuario_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
empleado_id         INT NOT NULL,
usuario             VARCHAR(100) NOT NULL,
contrasena          VARCHAR(200) NOT NULL,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_usuarios_empleado
FOREIGN KEY (empleado_id)
REFERENCES empleados (empleado_id),

CONSTRAINT uq_usuarios_usuario
UNIQUE (usuario)
);

-- HISTORIAL ALERTAS
CREATE TABLE historial_alertas (
alerta_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
usuario_id          INT,
tipo                VARCHAR(60) NOT NULL,
titulo              VARCHAR(150) NOT NULL,
mensaje             VARCHAR(300) NOT NULL,
modulo              VARCHAR(100) NOT NULL,
referencia_id       INT,
prioridad           VARCHAR(30) NOT NULL DEFAULT 'Media',
leida               BOOLEAN NOT NULL DEFAULT FALSE,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_historial_alertas_usuario
FOREIGN KEY (usuario_id)
REFERENCES usuarios (usuario_id),

CONSTRAINT chk_historial_alertas_prioridad
CHECK (prioridad IN ('Baja', 'Media', 'Alta'))
);

-- COMPRAS
CREATE TABLE compras (
compra_id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
proveedor_id        INT NOT NULL,
empleado_id         INT,
numero_factura      VARCHAR(50) NOT NULL,
fecha_compra        DATE NOT NULL DEFAULT CURRENT_DATE,
monto_total         NUMERIC(18,2) NOT NULL DEFAULT 0,
estado              VARCHAR(50) NOT NULL DEFAULT 'Pendiente',
observaciones       VARCHAR(200),
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_compras_proveedor
FOREIGN KEY (proveedor_id)
REFERENCES proveedores (proveedor_id),

CONSTRAINT fk_compras_empleado
FOREIGN KEY (empleado_id)
REFERENCES empleados (empleado_id),

CONSTRAINT uq_compras_numero_factura
UNIQUE (numero_factura),

CONSTRAINT chk_compras_monto
CHECK (monto_total >= 0),

CONSTRAINT chk_compras_estado
CHECK (estado IN ('Pendiente','Pagada','Cancelada'))
);

-- DETALLES COMPRAS
CREATE TABLE detalles_compras (
detalle_compra_id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
compra_id           INT NOT NULL,
material_id         INT NOT NULL,
cantidad            INT NOT NULL,
precio_unitario     NUMERIC(18,2) NOT NULL,

subtotal NUMERIC(18,2)
GENERATED ALWAYS AS (
cantidad * precio_unitario
) STORED,

fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_detalle_compra
FOREIGN KEY (compra_id)
REFERENCES compras (compra_id),

CONSTRAINT fk_detalle_materiales_comp
FOREIGN KEY (material_id)
REFERENCES materiales (material_id),

CONSTRAINT chk_detalles_compras_cantidad
CHECK (cantidad > 0),

CONSTRAINT chk_detalles_compras_precio
CHECK (precio_unitario > 0)
);

-- DETALLES AVALUOS
CREATE TABLE detalles_avaluos (
detalle_avaluo_id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
avaluo_id             INT NOT NULL,
servicio_id           INT NOT NULL,
actividad             VARCHAR(100) NOT NULL,
unidad_de_medida      VARCHAR(50) NOT NULL,
cantidad              INT NOT NULL,
precio_unitario       NUMERIC(18,2) NOT NULL,

costo_venta NUMERIC(18,2)
GENERATED ALWAYS AS (
cantidad * precio_unitario
) STORED,

iva NUMERIC(18,2)
GENERATED ALWAYS AS (
(cantidad * precio_unitario) * 0.15
) STORED,

total_costo_venta NUMERIC(18,2)
GENERATED ALWAYS AS (
(cantidad * precio_unitario) +
((cantidad * precio_unitario) * 0.15)
) STORED,

observaciones         VARCHAR(200),
fecha_creacion        TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion   TIMESTAMPTZ,
fecha_eliminacion     TIMESTAMPTZ,

CONSTRAINT fk_as_avaluo
FOREIGN KEY (avaluo_id)
REFERENCES avaluos (avaluo_id),

CONSTRAINT fk_as_servicio
FOREIGN KEY (servicio_id)
REFERENCES servicios (servicio_id),

CONSTRAINT chk_detalles_avaluos_cantidad
CHECK (cantidad > 0),

CONSTRAINT chk_detalles_avaluos_precio
CHECK (precio_unitario >= 0)
);

-- MENU
CREATE TABLE menu (
id_menu        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
nombre         VARCHAR(100) NOT NULL,
es_submenu     BOOLEAN DEFAULT FALSE,
url            VARCHAR(150),
id_menu_parent INT,
estado         BOOLEAN DEFAULT TRUE,
show           BOOLEAN DEFAULT TRUE,

CONSTRAINT fk_menu_parent
FOREIGN KEY (id_menu_parent)
REFERENCES menu (id_menu)
ON DELETE SET NULL
);

-- PERMISOS
CREATE TABLE permisos (
permiso_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
usuario_id          INT NOT NULL,
id_menu             INT NOT NULL,
estado              BOOLEAN DEFAULT TRUE,
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_perm_usuario
FOREIGN KEY (usuario_id)
REFERENCES usuarios (usuario_id)
ON DELETE CASCADE,

CONSTRAINT fk_perm_menu
FOREIGN KEY (id_menu)
REFERENCES menu (id_menu)
ON DELETE CASCADE,

CONSTRAINT permisos_unique
UNIQUE (usuario_id, id_menu)
);

-- MOVIMIENTOS INVENTARIO
CREATE TABLE movimientos_inventario (
movimiento_id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
material_id          INT NOT NULL,
tipo_movimiento      VARCHAR(30) NOT NULL,
cantidad             INT NOT NULL,
stock_anterior       INT NOT NULL,
stock_nuevo          INT NOT NULL,
precio_unitario      NUMERIC(18,2),

costo_total          NUMERIC(18,2)
GENERATED ALWAYS AS (
cantidad * precio_unitario
) STORED,

referencia           VARCHAR(100),
descripcion          VARCHAR(250),
usuario_id           INT,
fecha_movimiento     TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion  TIMESTAMPTZ,
fecha_eliminacion    TIMESTAMPTZ,

CONSTRAINT fk_movimientos_materiales
FOREIGN KEY (material_id)
REFERENCES materiales (material_id),

CONSTRAINT fk_movimientos_usuarios
FOREIGN KEY (usuario_id)
REFERENCES usuarios (usuario_id),

CONSTRAINT chk_movimientos_tipo
CHECK (tipo_movimiento IN ('Entrada', 'Salida', 'Ajuste')),

CONSTRAINT chk_movimientos_cantidad
CHECK (cantidad > 0),

CONSTRAINT chk_movimientos_stock_nuevo
CHECK (stock_nuevo >= 0)
);

-- REPORTES GENERADOS
CREATE TABLE reportes_generados (
reporte_id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
usuario_id          INT NOT NULL,
nombre_reporte      VARCHAR(150) NOT NULL,
tipo_reporte        VARCHAR(20) NOT NULL,
descripcion         VARCHAR(200),
datos               JSONB,
archivo_url         VARCHAR(255) NOT NULL,
ip_generacion       VARCHAR(50),
fecha_creacion      TIMESTAMPTZ DEFAULT NOW(),
fecha_actualizacion TIMESTAMPTZ,
fecha_eliminacion   TIMESTAMPTZ,

CONSTRAINT fk_reporte_usuario
FOREIGN KEY (usuario_id)
REFERENCES usuarios (usuario_id),

CONSTRAINT chk_reportes_tipo
CHECK (tipo_reporte IN ('PDF','EXCEL'))
);

-- ============================================================
-- 3. ÍNDICES RECOMENDADOS
-- No reemplazan los UNIQUE, pero ayudan al rendimiento
-- ============================================================

CREATE INDEX IF NOT EXISTS idx_empleados_rol_id
ON public.empleados (rol_id);

CREATE INDEX IF NOT EXISTS idx_empleados_reportes
ON public.empleados (reportes);

CREATE INDEX IF NOT EXISTS idx_proveedores_categoria_id
ON public.proveedores (categoria_proveedor_id);

CREATE INDEX IF NOT EXISTS idx_proyectos_cliente_id
ON public.proyectos (cliente_id);

CREATE INDEX IF NOT EXISTS idx_detalles_empleados_empleado_id
ON public.detalles_empleados (empleado_id);

CREATE INDEX IF NOT EXISTS idx_detalles_empleados_proyecto_id
ON public.detalles_empleados (proyecto_id);

CREATE INDEX IF NOT EXISTS idx_materiales_categoria_id
ON public.materiales (categoria_id);

CREATE INDEX IF NOT EXISTS idx_alertas_inventario_material_id
ON public.alertas_inventario (material_id);

CREATE INDEX IF NOT EXISTS idx_alertas_inventario_estado
ON public.alertas_inventario (estado);

CREATE INDEX IF NOT EXISTS idx_avaluos_proyecto_id
ON public.avaluos (proyecto_id);

CREATE INDEX IF NOT EXISTS idx_costos_directos_servicio_id
ON public.costos_directos_servicios (servicio_id);

CREATE INDEX IF NOT EXISTS idx_costos_directos_material_id
ON public.costos_directos_servicios (material_id);

CREATE INDEX IF NOT EXISTS idx_costos_indirectos_servicio_id
ON public.costos_indirectos_servicios (servicio_id);

CREATE INDEX IF NOT EXISTS idx_costos_indirectos_costo_directo_id
ON public.costos_indirectos_servicios (costo_directo_id);

CREATE INDEX IF NOT EXISTS idx_maquinarias_proveedor_id
ON public.maquinarias (proveedor_id);

CREATE INDEX IF NOT EXISTS idx_detalles_maquinarias_proyecto_id
ON public.detalles_maquinarias (proyecto_id);

CREATE INDEX IF NOT EXISTS idx_detalles_maquinarias_maquinaria_id
ON public.detalles_maquinarias (maquinaria_id);

CREATE INDEX IF NOT EXISTS idx_vehiculos_proveedor_id
ON public.vehiculos (proveedor_id);

CREATE INDEX IF NOT EXISTS idx_detalles_vehiculos_empleado_id
ON public.detalles_vehiculos (empleado_id);

CREATE INDEX IF NOT EXISTS idx_detalles_vehiculos_vehiculo_id
ON public.detalles_vehiculos (vehiculo_id);

CREATE INDEX IF NOT EXISTS idx_usuarios_empleado_id
ON public.usuarios (empleado_id);

CREATE INDEX IF NOT EXISTS idx_historial_alertas_usuario_id
ON public.historial_alertas (usuario_id);

CREATE INDEX IF NOT EXISTS idx_historial_alertas_modulo
ON public.historial_alertas (modulo);

CREATE INDEX IF NOT EXISTS idx_historial_alertas_leida
ON public.historial_alertas (leida);

CREATE INDEX IF NOT EXISTS idx_compras_proveedor_id
ON public.compras (proveedor_id);

CREATE INDEX IF NOT EXISTS idx_compras_empleado_id
ON public.compras (empleado_id);

CREATE INDEX IF NOT EXISTS idx_detalles_compras_compra_id
ON public.detalles_compras (compra_id);

CREATE INDEX IF NOT EXISTS idx_detalles_compras_material_id
ON public.detalles_compras (material_id);

CREATE INDEX IF NOT EXISTS idx_detalles_avaluos_avaluo_id
ON public.detalles_avaluos (avaluo_id);

CREATE INDEX IF NOT EXISTS idx_detalles_avaluos_servicio_id
ON public.detalles_avaluos (servicio_id);

CREATE INDEX IF NOT EXISTS idx_permisos_usuario_id
ON public.permisos (usuario_id);

CREATE INDEX IF NOT EXISTS idx_permisos_menu_id
ON public.permisos (id_menu);

CREATE INDEX IF NOT EXISTS idx_movimientos_inventario_material_id
ON public.movimientos_inventario (material_id);

CREATE INDEX IF NOT EXISTS idx_movimientos_inventario_usuario_id
ON public.movimientos_inventario (usuario_id);

CREATE INDEX IF NOT EXISTS idx_movimientos_inventario_fecha
ON public.movimientos_inventario (fecha_movimiento);

CREATE INDEX IF NOT EXISTS idx_reportes_usuario_id
ON public.reportes_generados (usuario_id);


-- ============================================================
-- 4. FUNCIÓN PARA ACTUALIZAR FECHA_ACTUALIZACION
-- ============================================================

CREATE OR REPLACE FUNCTION public.actualizar_fecha_modificacion()
RETURNS TRIGGER AS $$
BEGIN
    NEW.fecha_actualizacion = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 5. TRIGGERS PARA FECHA_ACTUALIZACION
-- ============================================================

DROP TRIGGER IF EXISTS trg_roles_update ON public.roles;
CREATE TRIGGER trg_roles_update
BEFORE UPDATE ON public.roles
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_empleados_update ON public.empleados;
CREATE TRIGGER trg_empleados_update
BEFORE UPDATE ON public.empleados
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_clientes_update ON public.clientes;
CREATE TRIGGER trg_clientes_update
BEFORE UPDATE ON public.clientes
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_categorias_proveedor_update ON public.categorias_proveedor;
CREATE TRIGGER trg_categorias_proveedor_update
BEFORE UPDATE ON public.categorias_proveedor
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_proveedores_update ON public.proveedores;
CREATE TRIGGER trg_proveedores_update
BEFORE UPDATE ON public.proveedores
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_categorias_update ON public.categorias;
CREATE TRIGGER trg_categorias_update
BEFORE UPDATE ON public.categorias
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_proyectos_update ON public.proyectos;
CREATE TRIGGER trg_proyectos_update
BEFORE UPDATE ON public.proyectos
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_detalles_empleados_update ON public.detalles_empleados;
CREATE TRIGGER trg_detalles_empleados_update
BEFORE UPDATE ON public.detalles_empleados
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_materiales_update ON public.materiales;
CREATE TRIGGER trg_materiales_update
BEFORE UPDATE ON public.materiales
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_alertas_inventario_update ON public.alertas_inventario;
CREATE TRIGGER trg_alertas_inventario_update
BEFORE UPDATE ON public.alertas_inventario
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_avaluos_update ON public.avaluos;
CREATE TRIGGER trg_avaluos_update
BEFORE UPDATE ON public.avaluos
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_servicios_update ON public.servicios;
CREATE TRIGGER trg_servicios_update
BEFORE UPDATE ON public.servicios
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_costos_directos_update ON public.costos_directos_servicios;
CREATE TRIGGER trg_costos_directos_update
BEFORE UPDATE ON public.costos_directos_servicios
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_costos_indirectos_update ON public.costos_indirectos_servicios;
CREATE TRIGGER trg_costos_indirectos_update
BEFORE UPDATE ON public.costos_indirectos_servicios
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_detalles_avaluos_update ON public.detalles_avaluos;
CREATE TRIGGER trg_detalles_avaluos_update
BEFORE UPDATE ON public.detalles_avaluos
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_maquinarias_update ON public.maquinarias;
CREATE TRIGGER trg_maquinarias_update
BEFORE UPDATE ON public.maquinarias
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_detalles_maquinarias_update ON public.detalles_maquinarias;
CREATE TRIGGER trg_detalles_maquinarias_update
BEFORE UPDATE ON public.detalles_maquinarias
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_vehiculos_update ON public.vehiculos;
CREATE TRIGGER trg_vehiculos_update
BEFORE UPDATE ON public.vehiculos
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_detalles_vehiculos_update ON public.detalles_vehiculos;
CREATE TRIGGER trg_detalles_vehiculos_update
BEFORE UPDATE ON public.detalles_vehiculos
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_usuarios_update ON public.usuarios;
CREATE TRIGGER trg_usuarios_update
BEFORE UPDATE ON public.usuarios
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_historial_alertas_update ON public.historial_alertas;
CREATE TRIGGER trg_historial_alertas_update
BEFORE UPDATE ON public.historial_alertas
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_permisos_update ON public.permisos;
CREATE TRIGGER trg_permisos_update
BEFORE UPDATE ON public.permisos
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_compras_update ON public.compras;
CREATE TRIGGER trg_compras_update
BEFORE UPDATE ON public.compras
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_detalles_compras_update ON public.detalles_compras;
CREATE TRIGGER trg_detalles_compras_update
BEFORE UPDATE ON public.detalles_compras
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_movimientos_inventario_update ON public.movimientos_inventario;
CREATE TRIGGER trg_movimientos_inventario_update
BEFORE UPDATE ON public.movimientos_inventario
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();

DROP TRIGGER IF EXISTS trg_reportes_generados_update ON public.reportes_generados;
CREATE TRIGGER trg_reportes_generados_update
BEFORE UPDATE ON public.reportes_generados
FOR EACH ROW
EXECUTE FUNCTION public.actualizar_fecha_modificacion();


-- ============================================================
-- 6. FUNCIÓN PARA GENERAR ALERTAS DE INVENTARIO
-- ============================================================

CREATE OR REPLACE FUNCTION public.generar_alerta_stock_bajo()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.cantidad_en_stock <= NEW.stock_minimo THEN

        INSERT INTO public.alertas_inventario (
            material_id,
            tipo_alerta,
            mensaje,
            stock_actual,
            stock_minimo,
            estado,
            fecha_creacion
        )
        SELECT
            NEW.material_id,
            CASE
                WHEN NEW.cantidad_en_stock = NEW.stock_minimo THEN 'Stock Bajo'
                ELSE 'Inventario Crítico'
            END,
            'El material "' || NEW.nombre_material || '" alcanzó el inventario de seguridad. Stock actual: '
            || NEW.cantidad_en_stock || ', stock mínimo permitido: ' || NEW.stock_minimo || '.',
            NEW.cantidad_en_stock,
            NEW.stock_minimo,
            'Pendiente',
            NOW()
        WHERE NOT EXISTS (
            SELECT 1
            FROM public.alertas_inventario ai
            WHERE ai.material_id = NEW.material_id
            AND ai.estado = 'Pendiente'
        );

    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_alerta_stock_bajo ON public.materiales;

CREATE TRIGGER trg_alerta_stock_bajo
AFTER INSERT OR UPDATE OF cantidad_en_stock
ON public.materiales
FOR EACH ROW
EXECUTE FUNCTION public.generar_alerta_stock_bajo();


-- ============================================================
-- 7. FUNCIÓN PARA REGISTRAR ENTRADA DE MATERIAL
-- ============================================================

CREATE OR REPLACE FUNCTION public.registrar_entrada_material(
    p_material_id INTEGER,
    p_cantidad INTEGER,
    p_precio_unitario NUMERIC,
    p_referencia VARCHAR,
    p_descripcion VARCHAR,
    p_usuario_id INTEGER DEFAULT NULL
)
RETURNS VOID AS $$
DECLARE
    v_stock_anterior INTEGER;
    v_stock_nuevo INTEGER;
BEGIN
    IF p_cantidad <= 0 THEN
        RAISE EXCEPTION 'La cantidad de entrada debe ser mayor que cero.';
    END IF;

    SELECT cantidad_en_stock
    INTO v_stock_anterior
    FROM public.materiales
    WHERE material_id = p_material_id;

    IF v_stock_anterior IS NULL THEN
        RAISE EXCEPTION 'El material no existe.';
    END IF;

    v_stock_nuevo := v_stock_anterior + p_cantidad;

    UPDATE public.materiales
    SET cantidad_en_stock = v_stock_nuevo
    WHERE material_id = p_material_id;

    INSERT INTO public.movimientos_inventario (
        material_id,
        tipo_movimiento,
        cantidad,
        stock_anterior,
        stock_nuevo,
        precio_unitario,
        referencia,
        descripcion,
        usuario_id
    )
    VALUES (
        p_material_id,
        'Entrada',
        p_cantidad,
        v_stock_anterior,
        v_stock_nuevo,
        p_precio_unitario,
        p_referencia,
        p_descripcion,
        p_usuario_id
    );
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 8. FUNCIÓN PARA REGISTRAR SALIDA DE MATERIAL
-- ============================================================

CREATE OR REPLACE FUNCTION public.registrar_salida_material(
    p_material_id INTEGER,
    p_cantidad INTEGER,
    p_referencia VARCHAR,
    p_descripcion VARCHAR,
    p_usuario_id INTEGER DEFAULT NULL
)
RETURNS VOID AS $$
DECLARE
    v_stock_anterior INTEGER;
    v_stock_nuevo INTEGER;
    v_stock_minimo INTEGER;
    v_precio_unitario NUMERIC(18,2);
BEGIN
    IF p_cantidad <= 0 THEN
        RAISE EXCEPTION 'La cantidad de salida debe ser mayor que cero.';
    END IF;

    SELECT cantidad_en_stock, stock_minimo, precio_unitario
    INTO v_stock_anterior, v_stock_minimo, v_precio_unitario
    FROM public.materiales
    WHERE material_id = p_material_id;

    IF v_stock_anterior IS NULL THEN
        RAISE EXCEPTION 'El material no existe.';
    END IF;

    v_stock_nuevo := v_stock_anterior - p_cantidad;

    IF v_stock_nuevo < v_stock_minimo THEN
        RAISE EXCEPTION 'Movimiento no permitido. El inventario no puede ser menor a % unidades. Stock actual: %, salida solicitada: %, stock resultante: %.',
            v_stock_minimo, v_stock_anterior, p_cantidad, v_stock_nuevo;
    END IF;

    UPDATE public.materiales
    SET cantidad_en_stock = v_stock_nuevo
    WHERE material_id = p_material_id;

    INSERT INTO public.movimientos_inventario (
        material_id,
        tipo_movimiento,
        cantidad,
        stock_anterior,
        stock_nuevo,
        precio_unitario,
        referencia,
        descripcion,
        usuario_id
    )
    VALUES (
        p_material_id,
        'Salida',
        p_cantidad,
        v_stock_anterior,
        v_stock_nuevo,
        v_precio_unitario,
        p_referencia,
        p_descripcion,
        p_usuario_id
    );
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 9. FUNCIÓN PARA REGISTRAR AJUSTE DE MATERIAL
-- ============================================================

CREATE OR REPLACE FUNCTION public.registrar_ajuste_material(
    p_material_id INTEGER,
    p_stock_nuevo INTEGER,
    p_referencia VARCHAR,
    p_descripcion VARCHAR,
    p_usuario_id INTEGER DEFAULT NULL
)
RETURNS VOID AS $$
DECLARE
    v_stock_anterior INTEGER;
    v_stock_minimo INTEGER;
    v_diferencia INTEGER;
    v_precio_unitario NUMERIC(18,2);
BEGIN
    SELECT cantidad_en_stock, stock_minimo, precio_unitario
    INTO v_stock_anterior, v_stock_minimo, v_precio_unitario
    FROM public.materiales
    WHERE material_id = p_material_id;

    IF v_stock_anterior IS NULL THEN
        RAISE EXCEPTION 'El material no existe.';
    END IF;

    IF p_stock_nuevo < v_stock_minimo THEN
        RAISE EXCEPTION 'Ajuste no permitido. El inventario no puede ser menor a % unidades.', v_stock_minimo;
    END IF;

    v_diferencia := ABS(p_stock_nuevo - v_stock_anterior);

    UPDATE public.materiales
    SET cantidad_en_stock = p_stock_nuevo
    WHERE material_id = p_material_id;

    INSERT INTO public.movimientos_inventario (
        material_id,
        tipo_movimiento,
        cantidad,
        stock_anterior,
        stock_nuevo,
        precio_unitario,
        referencia,
        descripcion,
        usuario_id
    )
    VALUES (
        p_material_id,
        'Ajuste',
        v_diferencia,
        v_stock_anterior,
        p_stock_nuevo,
        v_precio_unitario,
        p_referencia,
        p_descripcion,
        p_usuario_id
    );
END;
$$ LANGUAGE plpgsql;


-- ============================================================
-- 10. FUNCIÓN PARA REGISTRAR ENTRADA DESDE DETALLES_COMPRAS
-- ============================================================

CREATE OR REPLACE FUNCTION public.registrar_entrada_desde_compra()
RETURNS TRIGGER AS $$
DECLARE
    v_stock_anterior INTEGER;
    v_stock_nuevo INTEGER;
    v_factura VARCHAR(50);
BEGIN
    SELECT cantidad_en_stock
    INTO v_stock_anterior
    FROM public.materiales
    WHERE material_id = NEW.material_id;

    IF v_stock_anterior IS NULL THEN
        RAISE EXCEPTION 'El material no existe.';
    END IF;

    v_stock_nuevo := v_stock_anterior + NEW.cantidad;

    UPDATE public.materiales
    SET cantidad_en_stock = v_stock_nuevo
    WHERE material_id = NEW.material_id;

    SELECT numero_factura
    INTO v_factura
    FROM public.compras
    WHERE compra_id = NEW.compra_id;

    INSERT INTO public.movimientos_inventario (
        material_id,
        tipo_movimiento,
        cantidad,
        stock_anterior,
        stock_nuevo,
        precio_unitario,
        referencia,
        descripcion,
        usuario_id
    )
    VALUES (
        NEW.material_id,
        'Entrada',
        NEW.cantidad,
        v_stock_anterior,
        v_stock_nuevo,
        NEW.precio_unitario,
        'Compra ' || COALESCE(v_factura, NEW.compra_id::TEXT),
        'Entrada automática generada desde detalle de compra.',
        NULL
    );

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_entrada_desde_compra ON public.detalles_compras;

CREATE TRIGGER trg_entrada_desde_compra
AFTER INSERT ON public.detalles_compras
FOR EACH ROW
EXECUTE FUNCTION public.registrar_entrada_desde_compra();

-- ============================================================
-- 1. CORREGIR EMPLEADOS QUE USAN ROLES DUPLICADOS
-- ============================================================

UPDATE public.empleados e
SET rol_id = r_min.rol_id_min
FROM (
    SELECT cargo, MIN(rol_id) AS rol_id_min
    FROM public.roles
    GROUP BY cargo
) r_min
JOIN public.roles r_dup
ON r_dup.cargo = r_min.cargo
WHERE e.rol_id = r_dup.rol_id
AND r_dup.rol_id <> r_min.rol_id_min;


-- ============================================================
-- 2. ELIMINAR ROLES DUPLICADOS
-- Se conserva el rol con menor rol_id
-- ============================================================

DELETE FROM public.roles r
USING public.roles r2
WHERE r.rol_id > r2.rol_id
AND r.cargo = r2.cargo;


-- ============================================================
-- 3. CORREGIR MATERIALES QUE USAN CATEGORÍAS DUPLICADAS
-- ============================================================

UPDATE public.materiales m
SET categoria_id = c_min.categoria_id_min
FROM (
    SELECT nombre_categoria, MIN(categoria_id) AS categoria_id_min
    FROM public.categorias
    GROUP BY nombre_categoria
) c_min
JOIN public.categorias c_dup
ON c_dup.nombre_categoria = c_min.nombre_categoria
WHERE m.categoria_id = c_dup.categoria_id
AND c_dup.categoria_id <> c_min.categoria_id_min;


-- ============================================================
-- 4. ELIMINAR CATEGORÍAS DUPLICADAS
-- Se conserva la categoría con menor categoria_id
-- ============================================================

DELETE FROM public.categorias c
USING public.categorias c2
WHERE c.categoria_id > c2.categoria_id
AND c.nombre_categoria = c2.nombre_categoria;


-- ============================================================
-- 5. CORREGIR PROVEEDORES QUE USAN CATEGORÍAS PROVEEDOR DUPLICADAS
-- ============================================================

UPDATE public.proveedores p
SET categoria_proveedor_id = cp_min.categoria_proveedor_id_min
FROM (
    SELECT nombre_categoria, MIN(categoria_proveedor_id) AS categoria_proveedor_id_min
    FROM public.categorias_proveedor
    GROUP BY nombre_categoria
) cp_min
JOIN public.categorias_proveedor cp_dup
ON cp_dup.nombre_categoria = cp_min.nombre_categoria
WHERE p.categoria_proveedor_id = cp_dup.categoria_proveedor_id
AND cp_dup.categoria_proveedor_id <> cp_min.categoria_proveedor_id_min;


-- ============================================================
-- 6. ELIMINAR CATEGORÍAS PROVEEDOR DUPLICADAS
-- Se conserva la categoría con menor categoria_proveedor_id
-- ============================================================

DELETE FROM public.categorias_proveedor cp
USING public.categorias_proveedor cp2
WHERE cp.categoria_proveedor_id > cp2.categoria_proveedor_id
AND cp.nombre_categoria = cp2.nombre_categoria;